name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    runs-on: ubuntu-latest
    container: vitasdk/vitasdk-softfp:latest
    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        git clone https://github.com/frangarcj/opensles
        make -C opensles/libopensles -j$(nproc) install
        git clone https://github.com/Rinnegatamante/vitaGL.git
        make -C vitaGL SOFTFP_ABI=1 NO_DEBUG=1 NO_TEX_COMBINER=1 MATH_SPEEDHACK=1 -j$(nproc) install
    - name: Get Information Variables
      id: core
      run: |
        echo "::set-output name=sha8::$(echo ${GITHUB_SHA} | cut -c1-8)"
    - name: Compile project
      run: |
        mkdir build
        cd build
        cmake ..
        make -j$(nproc)
    - name: Upload artifacts
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: FF3-${{ steps.core.outputs.sha8 }}.vpk
        path: build/FF3.vpk
    - uses: svenstaro/upload-release-action@v2
      if: contains(github.ref,'refs/tags')
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: build/FF3.vpk
        overwrite: true
        tag: ${{ github.ref }}
